kind: Secret 
apiVersion: v1 
metadata: 
  name: secret 
  namespace: govt-ip 
type: Opaque 
stringData: 
  mongo-password: admin123
  mongo-uri: mongodb://admin:admin123@mongo-service:27017/govt-ip?authSource=admin
